version: '3.4'

services:
  projects:
    build:
      dockerfile:  ./server/CRM_hack/projects/Dockerfile
    ports:
      - "8082:8082"
    restart: always

  client:
    build:
      dockerfile: dockerfile
      context: ./client
    container_name: reactClient
    ports:
      - "8081:3000"
    restart: always